//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace petro_home_back.Resources {
    using System;
    
    
    /// <summary>
    ///   지역화된 문자열 등을 찾기 위한 강력한 형식의 리소스 클래스입니다.
    /// </summary>
    // 이 클래스는 ResGen 또는 Visual Studio와 같은 도구를 통해 StronglyTypedResourceBuilder
    // 클래스에서 자동으로 생성되었습니다.
    // 멤버를 추가하거나 제거하려면 .ResX 파일을 편집한 다음 /str 옵션을 사용하여 ResGen을
    // 다시 실행하거나 VS 프로젝트를 다시 빌드하십시오.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Exception_ko {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Exception_ko() {
        }
        
        /// <summary>
        ///   이 클래스에서 사용하는 캐시된 ResourceManager 인스턴스를 반환합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("petro_home_back.Resources.Exception_ko", typeof(Exception_ko).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   이 강력한 형식의 리소스 클래스를 사용하여 모든 리소스 조회에 대해 현재 스레드의 CurrentUICulture 속성을
        ///   재정의합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   -1004과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string AccessDenied {
            get {
                return ResourceManager.GetString("AccessDenied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   보유한 권한으로 접근할 수 없는 리소스 입니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string AccessDeniedMsg {
            get {
                return ResourceManager.GetString("AccessDeniedMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   -1005과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string CommunicationError {
            get {
                return ResourceManager.GetString("CommunicationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   통신 중 오류가 발생하였습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string CommunicationErrorMsg {
            get {
                return ResourceManager.GetString("CommunicationErrorMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   -1003과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string EntryPoint {
            get {
                return ResourceManager.GetString("EntryPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   해당 리소스에 접근하기 위한 권한이 없습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string EntryPointMsg {
            get {
                return ResourceManager.GetString("EntryPointMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   -1011과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ExpiredUser {
            get {
                return ResourceManager.GetString("ExpiredUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   로그인이 만료되었습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ExpiredUserMsg {
            get {
                return ResourceManager.GetString("ExpiredUserMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   -1010과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string FileDownload {
            get {
                return ResourceManager.GetString("FileDownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   파일 다운로드에 실패했습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string FileDownloadMsg {
            get {
                return ResourceManager.GetString("FileDownloadMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   -1009과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string FileUpload {
            get {
                return ResourceManager.GetString("FileUpload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   파일 업로드에 실패했습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string FileUploadMsg {
            get {
                return ResourceManager.GetString("FileUploadMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   -1008과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ForbiddenWord {
            get {
                return ResourceManager.GetString("ForbiddenWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   입력한 내용에 금칙어가 포함되어 있습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ForbiddenWordMsg {
            get {
                return ResourceManager.GetString("ForbiddenWordMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   -1007과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string NotOwner {
            get {
                return ResourceManager.GetString("NotOwner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   접근 권한이 없거나, 소유의 리소스가 아닙니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string NotOwnerMsg {
            get {
                return ResourceManager.GetString("NotOwnerMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   -1006과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ResourceNotExist {
            get {
                return ResourceManager.GetString("ResourceNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   리소스가 존재하지 않습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ResourceNotExistMsg {
            get {
                return ResourceManager.GetString("ResourceNotExistMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   -1001과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string SignInFailed {
            get {
                return ResourceManager.GetString("SignInFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   계정이 존재하지 않거나, 비밀번호가 맞지 않습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string SignInFailedMsg {
            get {
                return ResourceManager.GetString("SignInFailedMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   -1002과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string SignUpFailed {
            get {
                return ResourceManager.GetString("SignUpFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   이미 등록된 계정입니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string SignUpFailedMsg {
            get {
                return ResourceManager.GetString("SignUpFailedMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   -9999과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Unknown {
            get {
                return ResourceManager.GetString("Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   알 수 없는 오류가 발생하였습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string UnknownMsg {
            get {
                return ResourceManager.GetString("UnknownMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   -1000과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string UserNotFound {
            get {
                return ResourceManager.GetString("UserNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   존재하지 않는 회원입니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string UserNotFoundMsg {
            get {
                return ResourceManager.GetString("UserNotFoundMsg", resourceCulture);
            }
        }
    }
}
